### ISSUE TITLE
Question: how to set different font size between quote and author?

### ISSUE THREAD

**Issue by Radiorusack** [NotCookey/Quote2Image#1]
Question: how to set different font size between quote and author?
is it possible?
thanks

**Comment by NotCookey** [comment]
> Question: how to set different font size between quote and author? is it possible? thanks

Technically, it isn't possible yet. I haven't implemented that feature to allow custom selection of the font size for the quote and author. At the moment the `font_size` parameter applies to both the author and the quote. 

I shall also take that a suggestion for the library to add a separate option for font size to the author.

**Comment by Radiorusack** [comment]
Then, i want to ask about the background.. in this lib, the output image is blur.. can you tell me how to make the output not blur/just with original picture?

because i make design the quote-background from corel, if blur, the quote-frame-design look not good..

**Comment by hizbul25** [comment]
I think you may use small `font-size` for author than the quote.

**Comment by NotCookey** [comment]
> I think you may use small `font-size` for author than the quote.

Thats one way to do it. But I'll think of adding a custom font size selection for the author and quote.
