### ISSUE TITLE
Background color image?

### ISSUE THREAD

**Issue by Radiorusack** [NotCookey/Quote2Image#2]
hallo,
How to just to using the original color?

i want to using original background color that i design from corel.. how to disable function that convert to bright?

**Comment by NotCookey** [comment]
> hallo, How to just to using the original color?
> 
> i want to using original background color that i design from corel.. how to disable function that convert to bright?

Hello, and i'm sorry but i couldn't understand it properly what you meant by `using the original color`. The project doesn't have any function that changes the color of the background image. Could you please elaborate or explain what you actually meant. Or perhaps did you mean how you can use your own background image that you designed in corel?

if you are talking about using your own background image then, you can just change the value of the `image` parameter to your background image file.
```py
from Quote2Image import convert

# Font Size Default to 32, Height and Width by default is 612
img=convert(
	quote="Pooing keeps you healthy",
	author="Pee",
	fg="white",
	image="background_img.jpg",
	border_color="black",
	font_size=32,
	font_file=None,
	width=1080,
	height=450)

# Save The Image as a Png file
img.save("quote.png")
```

Or did you mean the blurry effect on the background image and want to disable that effect?

**Comment by Radiorusack** [comment]
example if i choose bg-image with dark blue color, then the result will be very bright blue... it converted the original color to very bright...

**Comment by NotCookey** [comment]
> example if i choose bg-image with dark blue color, then the result will be very bright blue... it converted the original color to very bright...

I have tested it, and it doesn't actually change the background image color. Perhaps you can try using some different background image file. But if i may could you please send me that background image file so i can use it to see why it doesn't work and gets altered.

Thank you!
