### ISSUE TITLE
How t resize the font depending on the number of characters?

### ISSUE THREAD

**Issue by giggioman00** [NotCookey/Quote2Image#5]
Hi,
I have a list of text quotes (and of course, they may be of various lenght, some may be shorter while others longer)
I was thinking to use this moduleto bulk print this quotes to image but I'm not sure if this module can handle text resize automatically. I guess longer the quote, the more the resize should be in order to fit into the image. But can this module handle this? How?

**Comment by NotCookey** [comment]
> Hi, I have a list of text quotes (and of course, they may be of various lenght, some may be shorter while others longer) I was thinking to use this moduleto bulk print this quotes to image but I'm not sure if this module can handle text resize automatically. I guess longer the quote, the more the resize should be in order to fit into the image. But can this module handle this? How?

The width and height of the image is specified by the user which means if you were to make the output image resize based on the length of the quote & author then you were to do some calculations and apply it. This isn't a feature yet but as you bought it up this seems like a really good idea. I will be looking into it and see if I could implement such a function to map the height and width as per the length.
